apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  labels:
    app: account-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-api
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
      - name: account-api
        image: pranoyk/account-api:1.0
        ports:
        - containerPort: 8080
