apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-api
  labels:
    app: account-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: account-api
  template:
    metadata:
      labels:
        app: account-api
    spec:
      containers:
      - name: account-api
        image: pranoyk/k8s-demo-account:1.2
        ports:
        - containerPort: 8081
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pg-db-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-db-secret
                key: POSTGRES_PASSWORD
        envFrom:
          - configMapRef:
              name: pg-db-configmap
