apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: pranoyk/k8s-demo-user:1.3
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: pg-db-secret
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pg-db-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-db-secret
                key: POSTGRES_PASSWORD
        envFrom:
          - configMapRef:
              name: pg-db-configmap
