apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app.kubernetes.io/name: user-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30017
