apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: pg-db-configmap
  labels:
    app: postgresdb
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: "5432"