apiVersion: v1
# Kind for service
kind: Service
metadata:
  # Name your service
  name: postgres-service
  labels:
    app: postgres-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # Pod to route service traffic  
  selector:
    app: postgresdb